; SAM Coupé - All ports
; ---------------------
;
; Include this file to include all of the others.
;
; Author: Simon Cooke (spectecjr@gmail.com)
; Licensed under the MIT license (see LICENSE file).

INCLUDE "base_l.z80"
INCLUDE "colours_l.z80"
INCLUDE "comms_l.z80"
INCLUDE "disk_l.z80"
INCLUDE "joystick_l.z80"
INCLUDE "keyboard_l.z80"
INCLUDE "lightpen_l.z80"
INCLUDE "sound_l.z80"
INCLUDE "externalmemory_l.z80"
INCLUDE "realtimeclock_l.z80"
